import type { Restaurant } from "@/types/restaurant";

export const restaurant: Restaurant = {
  id: "le-patio-de-cotonou",
  brand: {
    name: "Le Patio de Cotonou",
    slogan: "Cuisine béninoise, ambiance premium",
    description:
      "Un restaurant élégant à Cotonou qui met en valeur les saveurs du Bénin dans une atmosphère contemporaine et conviviale.",
    logo: "/images/restaurant/logo.svg",
    heroImage: "/images/restaurant/hero.jpg",
    tagline: "Cuisine du terroir, esprit moderne",
  },
  theme: {
    primary: "#F97316",
    primaryDark: "#EA580C",
    secondary: "#1C1917",
    accent: "#FED7AA",
    background: "#FFF7ED",
    surface: "#FFFFFF",
    text: "#1C1917",
    mutedText: "#78716C",
    buttonStyle: "rounded",
    cardStyle: "elevated",
    typography: {
      heading: "var(--font-display), Georgia, serif",
      body: "var(--font-body), Arial, sans-serif",
    },
  },
  contact: {
    phone: "+229 97 21 45 89",
    whatsapp: "+229 97 21 45 89",
    email: "bonjour@lepatio-cotonou.bj",
    address: "Avenue de la Marina, Cotonou",
    city: "Cotonou",
    country: "Bénin",
    hours: [
      "Lundi - Vendredi : 12:00 - 22:00",
      "Samedi - Dimanche : 11:30 - 23:00",
    ],
    mapUrl: "https://maps.google.com/?q=Cotonou%20B%C3%A9nin",
    mapEmbedUrl: "https://www.google.com/maps?q=Cotonou%20B%C3%A9nin&output=embed",
  },
  contactSection: {
    label: "Contact",
    title: "Réservez votre prochaine table",
    intro:
      "Une expérience conviviale, généreuse et raffinée, pensée pour les repas entre amis, en famille ou en petit comité.",
  },
  openingHours: [
    { day: "Lundi", open: "12:00", close: "22:00" },
    { day: "Mardi", open: "12:00", close: "22:00" },
    { day: "Mercredi", open: "12:00", close: "22:00" },
    { day: "Jeudi", open: "12:00", close: "22:30" },
    { day: "Vendredi", open: "12:00", close: "23:00" },
    { day: "Samedi", open: "11:30", close: "23:00" },
    { day: "Dimanche", open: "11:30", close: "21:30" },
  ],
  socialLinks: {
    instagram: "https://instagram.com/lepatio.cotonou",
    facebook: "https://facebook.com/lepatio.cotonou",
    tiktok: "https://tiktok.com/@lepatio.cotonou",
  },
  socials: [
    { label: "Instagram", href: "https://instagram.com/lepatio.cotonou", icon: "instagram" },
    { label: "Facebook", href: "https://facebook.com/lepatio.cotonou", icon: "facebook" },
    { label: "TikTok", href: "https://tiktok.com/@lepatio.cotonou", icon: "tiktok" },
  ],
  about: {
    label: "Notre histoire",
    title: "Une cuisine qui raconte le Bénin",
    paragraphs: [
      "Le Patio de Cotonou est né d’une passion pour les saveurs du terroir, revisitées avec élégance et précision.",
      "Chaque plat est préparé à partir de produits locaux, avec une attention particulière à la finesse des épices et à la générosité des portions.",
      "Au cœur de la ville, notre restaurant offre une expérience conviviale, douce et contemporaine, faite pour les grandes tablées comme pour les dîners intimes.",
    ],
    image: "/images/restaurant/about.jpg",
    highlights: [
      { id: "local", title: "Produits locaux", icon: "leaf" },
      { id: "homemade", title: "Cuisine faite maison", icon: "chef" },
      { id: "warm", title: "Cadre chaleureux", icon: "candle" },
    ],
    stats: [
      { label: "Années d'expérience", value: "12+" },
      { label: "Plats à la carte", value: "12" },
      { label: "Note moyenne", value: "4.9/5" },
    ],
  },
  menuSection: {
    eyebrow: "Menu",
    title: "Notre carte",
    intro: "Une cuisine généreuse, fidèle aux saveurs du Bénin, servie dans un cadre élégant et chaleureux.",
  },
  menu: [
    {
      id: "entrees",
      name: "Entrées",
      description: "Petits plats qui éveillent les papilles.",
      dishes: [
        {
          id: "aloko-aux-oignons",
          name: "Aloko aux oignons",
          description: "Bananes plantain frites, oignons caramélisés et piment doux.",
          price: 2900,
          category: "Entrées",
          image: "/images/restaurant/menu/aloko.jpg",
          alt: "Aloko aux oignons, bananes plantain frites et oignons au piment.",
        },
        {
          id: "wagashi-grille",
          name: "Wagashi grillé",
          description: "Délicieux met local grillé, généreux et parfumé aux épices du terroir.",
          price: 3400,
          category: "Entrées",
          image: "/images/restaurant/menu/wagashi.jpg",
          alt: "Wagashi grillé, spécialité locale chaude et parfumée.",
        },
        {
          id: "beignets-haricots",
          name: "Beignets de haricots",
          description: "Beignets croustillants, dorés et savoureux, parfaits à partager.",
          price: 2600,
          category: "Entrées",
          image: "/images/restaurant/menu/beignets-haricots.jpg",
          alt: "Beignets de haricots, entrée croustillante et garnie de haricots.",
        },
      ],
    },
    {
      id: "plats",
      name: "Plats",
      description: "Les favorites de la maison.",
      dishes: [
        {
          id: "poisson-braise",
          name: "Poisson braisé",
          description: "Poisson mijoté aux épices locales, servi avec oignon frais et citron.",
          price: 4200,
          category: "Plats",
          image: "/images/restaurant/menu/poisson-braise.jpg",
          alt: "Poisson braisé aux épices locales dans une sauce parfumée.",
          popular: true,
          badge: "Signature",
        },
        {
          id: "akassa-sauce-epicee",
          name: "Akassa sauce épicée",
          description: "Pâte de maïs moelleuse, nappée d’une sauce épicée et généreuse.",
          price: 3900,
          category: "Plats",
          image: "/images/restaurant/menu/akassa.jpg",
          alt: "Akassa servie avec une sauce épicée et des légumes frais.",
          popular: true,
        },
        {
          id: "pate-rouge-sauce-arachide",
          name: "Pâte rouge sauce arachide",
          description: "Pâte maison généreuse, sauce arachide veloutée et légumes cuits à point.",
          price: 6500,
          category: "Plats",
          image: "/images/restaurant/menu/pate-rouge.jpg",
          alt: "Pâte rouge avec sauce arachide, viande et légumes dans un plat généreux.",
        },
      ],
    },
    {
      id: "desserts",
      name: "Desserts",
      description: "Fins de repas légers et gourmands.",
      dishes: [
        {
          id: "mango-passion",
          name: "Mango passion",
          description: "Dessert frais à base de mangue, fruits tropicaux et crème légère.",
          price: 2200,
          category: "Desserts",
        },
        {
          id: "beignets-agoute",
          name: "Beignets aux graines",
          description: "Petits beignets croustillants et parfumés aux graines locales.",
          price: 1800,
          category: "Desserts",
        },
        {
          id: "ananas-grille",
          name: "Ananas grillé",
          description: "Ananas caramélisé, miel et menthe fraîche.",
          price: 2000,
          category: "Desserts",
          badge: "Saison",
        },
      ],
    },
    {
      id: "boissons",
      name: "Boissons",
      description: "Boissons fraîches et signatures de la maison.",
      dishes: [
        {
          id: "jus-ananas",
          name: "Jus d’ananas",
          description: "Boisson fraîche, naturelle et équilibrée.",
          price: 1500,
          category: "Boissons",
        },
        {
          id: "soda-mangue",
          name: "Soda mangue",
          description: "Boisson pétillante aux notes de mangue et de citron.",
          price: 1700,
          category: "Boissons",
        },
        {
          id: "the-gingembre",
          name: "Thé au gingembre",
          description: "Infusion chaude aux épices locales et citron.",
          price: 1600,
          category: "Boissons",
        },
      ],
    },
  ],
  popularDishes: [
    {
      id: "popular-poulet-yassa",
      name: "Poulet yassa",
      description: "Plat signature de la maison, acidulé et parfumé.",
      price: 6800,
      category: "Plats signature",
      popular: true,
      badge: "À emporter",
    },
    {
      id: "popular-poisson-palmiste",
      name: "Poisson au palmiste",
      description: "Sauce riche et généreuse, servie avec du riz parfumé.",
      price: 7200,
      category: "Plats signature",
      popular: true,
      badge: "Favori",
    },
    {
      id: "popular-riz-gombo",
      name: "Riz sauce gombo",
      description: "Un classique revisité aux saveurs du Bénin.",
      price: 5900,
      category: "Plats signature",
      popular: true,
      badge: "Populaire",
    },
  ],
  gallery: {
    label: "Galerie",
    title: "Un décor qui donne envie de s'attarder",
    intro: "Des saveurs généreuses, une lumière douce et un cadre premium pensés pour les moments à partager.",
    images: [
      {
        id: "gallery-terrasse",
        title: "Terrasse",
        src: "/images/restaurant/gallery/terrasse.jpg",
        alt: "Terrasse extérieure du restaurant Le Patio de Cotonou en soirée, ambiance premium et lumineuse.",
        span: "feature",
      },
      {
        id: "gallery-cocktail",
        title: "Cocktail",
        src: "/images/restaurant/gallery/cocktail.jpg",
        alt: "Cocktail coloré servi au restaurant dans une ambiance élégante.",
        span: "square",
      },
      {
        id: "gallery-table-groupe",
        title: "Table de groupe",
        src: "/images/restaurant/gallery/table-groupe.jpg",
        alt: "Grande table de groupe dressée avec élégance pour un dîner en famille ou entre amis.",
        span: "square",
      },
      {
        id: "gallery-brochette",
        title: "Brochette",
        src: "/images/restaurant/gallery/brochette.jpg",
        alt: "Assiette de brochette gastronomique servie avec des légumes et une présentation soignée.",
        span: "square",
      },
      {
        id: "gallery-dessert",
        title: "Dessert",
        src: "/images/restaurant/gallery/dessert.jpg",
        alt: "Dessert gourmand et finement présenté dans un cadre chaleureux.",
        span: "square",
      },
      {
        id: "gallery-salle",
        title: "Salle",
        src: "/images/restaurant/gallery/salle.jpg",
        alt: "Vue de la salle intérieure du restaurant, avec une décoration chic et conviviale.",
        span: "square",
      },
    ],
  },
  footer: {
    text: "Une cuisine béninoise généreuse, une ambiance premium et des moments à partager en cœur de ville.",
    hours: "Tous les jours · 12:00 – 23:00",
    links: [
      { label: "Le restaurant", href: "#about" },
      { label: "Menu", href: "#menu" },
      { label: "Galerie", href: "#gallery" },
      { label: "Contact", href: "#contact" },
    ],
  },
  testimonials: [
    {
      id: "testimonial-01",
      author: "Ariane Dossou",
      role: "Chef de marque",
      quote:
        "Un lieu inspirant où les saveurs locales sont sublimées. Le service est impeccable et l’ambiance très chic.",
      rating: 5,
    },
    {
      id: "testimonial-02",
      author: "Moussa Kouton",
      role: "Client régulier",
      quote:
        "Le poulet yassa est excellent et la terrasse est parfaite pour un dîner en famille. Très bon point de rendez-vous.",
      rating: 5,
    },
    {
      id: "testimonial-03",
      author: "Sophie Agbo",
      role: "Voyageuse",
      quote:
        "J’ai découvert la cuisine béninoise dans un cadre moderne. Très belle expérience, service attentionné et plats généreux.",
      rating: 5,
    },
  ],
};

export default restaurant;
